### ISSUE TITLE
Myrddin 0.92 shows 0.91 version!

### ISSUE THREAD

**Issue by toni-chess** [JVMerlino/Myrddin#2]
#-------------------------------#
# Myrddin 0.92  - (12/7/24)     #
# Copyright 2024 - John Merlino #
# All Rights Reserved           #
#-------------------------------#

feature done=0
info debug NN infos : Myrddin 0.91 by John Merlino (courtesy David Carteau)
>

**Comment by JVMerlino** [comment]
Hello, and thanks for the report. This isn't (really) a bug, although I admit it's confusing when you see it in the console. This text actually reports the version of the NN network, which didn't change between 0.91 and 0.92.

**Comment by toni-chess** [comment]
> Hello, and thanks for the report. This isn't (really) a bug, although I admit it's confusing when you see it in the console. This text actually reports the version of the NN network, which didn't change between 0.91 and 0.92.

oops, sorry, I didn't see it well, maybe I was sleepy. :)
You are right.
best regards!
